# Global Variables
before_script:
  - "apt-get update && apt-get install make live-build pbuilder devscripts python3-pystache python3-git --assume-yes"
  - "./configure --build-type release --build-by $(hostname -f)@$CI_RUNNER_DESCRIPTION --architecture amd64 --debian-mirror 'http://ftp.debian.org/debian/' --version $CI_JOB_ID.$CI_COMMIT_REF_SLUG-beryjuorg"
  - "cat build/build-config.json"
after_script:
  - "make clean"
  - "rm -rf build/cache/*"
  - "rm -rf ~/.gnupg/"
stages:
  - build
image: debian:8

build-iso:
  script:
    - make clean
    - make iso
    - mv build/live-image-amd64.hybrid.iso output/
    - echo "${CI_GPG_PRIVATE}" | gpg --import
    - echo "${CI_GPG_KEY}" | gpg --batch --yes --passphrase-fd 0 -a --output output/live-image-amd64.hybrid.iso.asc --detach-sig output/live-image-amd64.hybrid.iso
  stage: build
  artifacts:
    paths:
    - output/
    expire_in: 2 days

