# Global Variables
before_script:
  - "apt-get update && apt-get install make live-build pbuilder devscripts python3-pystache --assume-yes"
  - "./configure --build-type release --build-by $(whoami)@$(hostname -f) --architecture amd64 --debian-mirror 'http://ftp.debian.org/debian/' --version $CI_JOB_ID"
  - "cat build/build-config.json"
after_script:
  - "make clean"
  - "rm -rf build/cache/*"
stages:
  - build
image: debian:8

build-iso:
  script:
    - make clean
    - make iso
    - mv build/live-image-amd64.hybrid.iso vyos.iso
  stage: build
  artifacts:
    paths:
    - vyos.iso
    expire_in: 2 days

