# Global Variables
before_script:
  - "apt-get install make live-build pbuilder devscripts python3-pystache --assume-yes"
  - "./configure --build-type release --build-by support@beryju.org --architecture amd64 --debian-mirror 'http://ftp.debian.org/debian/'"
stages:
  - build
image: debian:8

build-iso:
  script:
    - make clean
    - make iso
  stage: build
  artifacts:
    paths:
    - build/live-image-amd64.hybrid.iso
    expire_in: 2 days

